### ISSUE TITLE
error while unpacking rr7

### ISSUE THREAD

**Issue by Tosyk** [Nenkai/RRUnpacker#1]
I'm getting this error all the time while unpacking:
```
<...>
- MainMenu2_Free -> Tex_MainMenu
- MainMenu2_Free -> Tex_GTATop
- MainMenu2_Free -> Tex_GTACourseCateSelect
[39/2088] MainMenu3_Free
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at RR7Unpacker.RRDecompressor.Decompress(Stream stream, UInt32 compressedSize, Span`1 output, UInt32 uncompressedSize)
   at RR7Unpacker.RR7Unpacker.ExtractContainers()
   at RR7Unpacker.Program.Main(String[] args)
```

my version is `NPUB30457`

how I can solve this?

**Comment by Nenkai** [comment]
Seems like a bug, will investigate

**Comment by Tosyk** [comment]
do you need some samples? I've tried several versions of the tool and get the same results.

**Comment by Nenkai** [comment]
I've just tried with the same game code: `NPUB30457`, `main.elf` on the latest tool release (2.0.2).
Seems to work correctly here.
```
<...>
- MainMenu2_Free -> Tex_MainMenu
- MainMenu2_Free -> Tex_GTATop
- MainMenu2_Free -> Tex_GTACourseCateSelect
[39/2088] MainMenu3_Free
- MainMenu3_Free -> Tex_Option
- MainMenu3_Free -> Tex_OptionAVPlayer
- MainMenu3_Free -> Tex_OptionController
- MainMenu3_Free -> Tex_OptionMiniGame
- MainMenu3_Free -> Tex_OptionRating
- MainMenu3_Free -> Tex_OptionSound
- MainMenu3_Free -> Tex_OptionSpeaker
- MainMenu3_Free -> Tex_OptionPopUp
- MainMenu3_Free -> Tex_OptionPopupStatus
- MainMenu3_Free -> Tex_OptionInstall
- MainMenu3_Free -> Tex_OptionUnit
- MainMenu3_Free -> Tex_OptionPopUpFlag
- MainMenu3_Free -> Tex_OptionPopUpMap
- MainMenu3_Free -> Tex_OnlineRoomSearch
- MainMenu3_Free -> Tex_OnlineSearchList
- MainMenu3_Free -> Tex_OnlineTop
- MainMenu3_Free -> Tex_OnlineRoom
- MainMenu3_Free -> Tex_OnlineRoomSetting
- MainMenu3_Free -> Tex_OnlineRoomMov
- MainMenu3_Free -> Tex_CommonSideBar
- MainMenu3_Free -> Tex_SaveTop
[40/2088] MainMenu4_Free
<...>
```
Perhaps your .DAT file is corrupted?

**Comment by Tosyk** [comment]
I downloaded it from here: http://zeus.dl.playstation.net/cdn/UP0700/NPUB30457_00/HMNgUwAnjFJPNEPcYdNkMUgGIQOSyvnrARNKmqQrUdJIOUjEuxjRBFEJRLJqaWlDElEjdJVDvuSyWwBSvUHtIPzScTykCoRIGAqOE.pkg. Also, I have another version I downloaded from archive.org which turned to be the same.

Every other games that are supported being extracted already, only this psn version is left.

It starts to unpack but gives error after 100mb or so.

**Comment by UB833** [comment]
I had a different error while unpacking RR7 with RRUnpacker I gave the correct syntax and I got this:

the following syntax I wrote:
RRUnpacker.exe rr7 -i RR7.DAT -e eboot.bin -g NPUB30457 -o extracted

Error code:
RRUnpacker for Ridge Racer PSP(V2)/6/7/PSVita & R:Racing Evolution - by Nenkai#9075

Unhandled exception. System.IO.EndOfStreamException: Could not read 4 bytes.
   at Syroot.BinaryData.StreamExtensions.FillBuffer(Stream stream, Int32 length)
   at RRUnpacker.TOC.RR7TableOfContents.ReadFileDescriptors(BinaryStream bs)
   at RRUnpacker.TOC.RR7TableOfContents.Read()
   at RRUnpacker.Program.RR7Action(RR7Verbs options)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at RRUnpacker.Program.Main(String[] args)

do you know what caused this?

**Comment by JustMLC4real** [comment]
Can confirm that this still happens with NPUB30457:

```
C:\Users\Roegi\Desktop\RRUnpacker.exe>RRUnpacker.exe rr7 -i rr7.dat -e main.elf -g NPEB00513 -o lol
RRUnpacker for Ridge Racer PSP(V2)/6/7/PSVita & R:Racing Evolution - by Nenkai#9075

Unhandled exception. System.IO.IOException: Er is geprobeerd de bestandsaanwijzer voor het begin van het bestand te plaatsen. : 'C:\Users\Roegi\Desktop\RRUnpacker.exe\main.elf'
   at System.IO.FileStream.SeekCore(SafeFileHandle fileHandle, Int64 offset, SeekOrigin origin, Boolean closeInvalidHandle)
   at System.IO.FileStream.Seek(Int64 offset, SeekOrigin origin)
   at RRUnpacker.TOC.RR7TableOfContents.ReadFileDescriptors(BinaryStream bs)
   at RRUnpacker.TOC.RR7TableOfContents.Read()
   at RRUnpacker.Program.RR7Action(RR7Verbs options)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at RRUnpacker.Program.Main(String[] args)
   ```
   
   Edit: Found a fix, you just need to run CMD as admin
